# Generated by Django 6.0.1 on 2026-02-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(max_length=500)),
                ('youtube_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
