# Generated by Django 6.0.1 on 2026-02-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripPlanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
