# Generated by Django 6.0.1 on 2026-03-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripPlanner', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
